services:
  playwright:
    build: .

    container_name: enterprise-playwright

    environment:
      ENVIRONMENT: ${ENVIRONMENT:-qa}
      BROWSER: ${BROWSER:-chromium}
      EXECUTION_TYPE: ${EXECUTION_TYPE:-ui}
      HEADLESS: ${HEADLESS:-true}

    volumes:
      - ./artifacts:/app/artifacts

    command: >
      pytest
      -m ${EXECUTION_TYPE}

    restart: "no"