"""
==============================================================
AI Response Model

Author : Shubham Pandey

Description:
------------
Represents the standardized response returned by an AI provider.

Different AI providers return responses in different formats.
This model converts those provider-specific responses into a
single, consistent structure that the framework can understand.

Responsibilities:
-----------------
✓ Store AI response data
✓ Standardize responses across AI providers
✓ Carry metadata such as execution time and token usage
==============================================================
"""

from dataclasses import dataclass
from typing import Optional


@dataclass
class AIResponse:
    """
    Represents the response returned by an AI provider.

    Every AI provider converts its native response into this
    standardized object before returning it to the framework.
    """

    # Indicates whether the AI request completed successfully.
    success: bool

    # Name of the AI provider.
    # Example: OpenAI, Groq, Ollama
    provider: str

    # AI model used to generate the response.
    # Example: gpt-5, llama3, gemma2
    model: str

    # Response generated by the AI model.
    response: str

    # Total tokens consumed by the request.
    tokens: int = 0

    # Time taken by the AI provider to process the request (in seconds).
    execution_time: float = 0.0

    # Error message, if the request failed.
    error: Optional[str] = None